name = "TSML"
uuid = "198dc43e-9e51-5cd7-9d40-d9794d335912"
authors = ["Paulito Palmes <ppalmes@gmail.com>"]
version = "2.4.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLBase = "f0e99cf1-93fa-52ec-9ecc-5026115318e0"
MLDataUtils = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
ArgParse = "0.5, 0.6"
CSV = "0.4, 0.5"
CodecBzip2 = "0.4, 0.5, 0.6"
DataFrames = "0.17, 0.18, 0.19"
DecisionTree = "0.8, 0.9"
FileIO = "1.0"
GR = "0.35, 0.36, 0.37, 0.38, 0.39, 0.40, 0.41"
HTTP = "0.6, 0.7, 0.8"
Impute = "0.1,0.2,0.3"
Interact = "0.9, 0.10"
IterTools = "1.1, 1.2"
JSON2 = "0.2, 0.3"
MLBase = "0.6, 0.7, 0.8"
MLDataUtils = "0.2, 0.3, 0.4, 0.5"
Plots = "0.25, 0.26, 0.27"
Reexport = "0.1, 0.2"
StatsBase = "0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
